services:
  postgresql:
    image: postgres
    container_name: database
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Test1234_
      POSTGRES_DB: movie_search_db
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - pgdata:/var/lib/postgresql/data



volumes:
  pgdata: