spring:
  application:
    name: movie-search

  datasource:
    url: jdbc:postgresql://localhost:5432/movie_search_db
    username: admin
    password: Test1234_
    hikari:
      connection-timeout: 5000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true



logging:
  level:
    org.hibernate.sql: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE